### PR TITLE
Little style fix

### PR DESCRIPTION
**Pull request by adelatorrefoss**

### CODE REVIEW

**Comment by piotrek1543** [comment]
Nowadays, this PR has no additional value, so I doubt it would be merged. @adelatorrefoss please, check if there's something more to change or you may also add some personal about testing. Maybe one more example ;-)

**Review by ghost — CHANGES_REQUESTED** [review]
Nowadays, this PR brings no additional value to project.

**Comment by dbacinski** [comment]
Link is broken due to this whitespace. Thanks for the fix.

**Comment by adelatorrefoss** [comment]
Thanks! Great job here! :smile:

**Pull request merged**
